# Generated by Django 4.0.4 on 2022-06-10 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_trip_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_api.state'),
            preserve_default=False,
        ),
    ]
