# Generated by Django 4.0.4 on 2022-06-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0004_activity_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='city',
            field=models.CharField(max_length=20),
        ),
    ]
