# Generated by Django 4.0.4 on 2022-06-13 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0005_alter_activity_city_alter_trip_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='fifty_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='app_api.fiftyuser'),
        ),
    ]
