# Generated by Django 4.0.4 on 2022-06-17 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0007_rename_picture_url_trippicture_image_url_delete_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trippicture',
            old_name='image_url',
            new_name='url',
        ),
    ]
