# Generated by Django 4.0.4 on 2022-06-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0008_rename_image_url_trippicture_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fiftyuser',
            old_name='image_url',
            new_name='url',
        ),
    ]
