# Generated by Django 4.0.4 on 2022-06-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0009_rename_image_url_fiftyuser_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='specific_location',
        ),
    ]
