# Generated by Django 4.0.4 on 2022-06-21 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0010_remove_activity_specific_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='completed',
        ),
        migrations.AlterField(
            model_name='ratereview',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='app_api.activity'),
        ),
    ]
